<?php


namespace Donate\Providers;


use Illuminate\Support\ServiceProvider;
use Donate\Hook\DonateHook;


class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[DonateHook::class,'handle'],18);
    }
}
